ex_app/urls.py
from django.urls import path
from . import views

app_name = 'ex_app'
urlpatterns = [
    path('hello/', views.hello, name='hello'),


    path('', views.item, name='item'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('cart/', views.cart, name='cart')
]

serverstart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ex_app/', include('ex_app.urls')),
    path('admin/', admin.site.urls),

]

ex_app/models.py
from django.db import models

# item model


class Item(models.Model):

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=500)
    item_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.item_name

ex_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item
from django.template import loader
# Create your views here.


def hello(request):
    return HttpResponse("hello world")


def item(request):
    item_list = Item.objects.all()
    context = {
        'item_list': item_list,
    }
    return render(request, 'ex_app_templates/index.html', context)


def detail(request, item_id):
    Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request, 'ex_app_templates/detail.html', context)


def cart(request):
    return HttpResponse('This is cart')

ex_app/templates/ex_app_templates/detail.html
{% if item %}
    <h1>{{ item.item_name }}</h1>
    <h2>{{ item.item_desc }}</h2>
    <h3>{{ item.item_price }}</h3>
{% else %}
    <p>No item found.</p>
{% endif %}

ex_app/templates/ex_app_templates/index.html
<ul>
    {% for Item in item_list %}
        <li>
            <a href="{% url 'ex_app:detail' Item.id %}">{{ Item.id }} -- {{ Item.item_name }}</a>
        </li>
    {% empty %}
        <li>No items found.</li>
    {% endfor %}
</ul>